[package]
name = "weecrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.4"
sha2 = "0.10.8"
aes-gcm = "0.10.3"
anyhow = "1.0.95"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "plain_header"
harness = false
